all:
	$(MAKE) -C "/home/arthur/Desktop/Desamparado/Solvers/2024/sequential/Timed_MAB_DC/kissat_mab_dc/build"
kissat:
	$(MAKE) -C "/home/arthur/Desktop/Desamparado/Solvers/2024/sequential/Timed_MAB_DC/kissat_mab_dc/build" kissat
tissat:
	$(MAKE) -C "/home/arthur/Desktop/Desamparado/Solvers/2024/sequential/Timed_MAB_DC/kissat_mab_dc/build" tissat
clean:
	rm -f "/home/arthur/Desktop/Desamparado/Solvers/2024/sequential/Timed_MAB_DC/kissat_mab_dc"/makefile
	-$(MAKE) -C "/home/arthur/Desktop/Desamparado/Solvers/2024/sequential/Timed_MAB_DC/kissat_mab_dc/build" clean
	rm -rf "/home/arthur/Desktop/Desamparado/Solvers/2024/sequential/Timed_MAB_DC/kissat_mab_dc/build"
coverage:
	$(MAKE) -C "/home/arthur/Desktop/Desamparado/Solvers/2024/sequential/Timed_MAB_DC/kissat_mab_dc/build" coverage
indent:
	$(MAKE) -C "/home/arthur/Desktop/Desamparado/Solvers/2024/sequential/Timed_MAB_DC/kissat_mab_dc/build" indent
test:
	$(MAKE) -C "/home/arthur/Desktop/Desamparado/Solvers/2024/sequential/Timed_MAB_DC/kissat_mab_dc/build" test
.PHONY: all clean coverage indent kissat test tissat
