all:
	$(MAKE) -C "/home/arthur/Desktop/Desamparado/Solvers/2024/sequential/wait_test_hkis/build"
kissat:
	$(MAKE) -C "/home/arthur/Desktop/Desamparado/Solvers/2024/sequential/wait_test_hkis/build" kissat
tissat:
	$(MAKE) -C "/home/arthur/Desktop/Desamparado/Solvers/2024/sequential/wait_test_hkis/build" tissat
clean:
	rm -f "/home/arthur/Desktop/Desamparado/Solvers/2024/sequential/wait_test_hkis"/makefile
	rm -f "/home/arthur/Desktop/Desamparado/Solvers/2024/sequential/wait_test_hkis"/src/makefile
	-$(MAKE) -C "/home/arthur/Desktop/Desamparado/Solvers/2024/sequential/wait_test_hkis/build" clean
	rm -rf "/home/arthur/Desktop/Desamparado/Solvers/2024/sequential/wait_test_hkis/build"
coverage:
	$(MAKE) -C "/home/arthur/Desktop/Desamparado/Solvers/2024/sequential/wait_test_hkis/build" coverage
format:
	$(MAKE) -C "/home/arthur/Desktop/Desamparado/Solvers/2024/sequential/wait_test_hkis/build" format
test:
	$(MAKE) -C "/home/arthur/Desktop/Desamparado/Solvers/2024/sequential/wait_test_hkis/build" test
.PHONY: all clean coverage format kissat test tissat
