all:
	$(MAKE) -C "/home/arthur/Desktop/Desamparado/Solvers/2024/sequential/Timed_Kissatsc2024/build"
kissat:
	$(MAKE) -C "/home/arthur/Desktop/Desamparado/Solvers/2024/sequential/Timed_Kissatsc2024/build" kissat
tissat:
	$(MAKE) -C "/home/arthur/Desktop/Desamparado/Solvers/2024/sequential/Timed_Kissatsc2024/build" tissat
clean:
	rm -f "/home/arthur/Desktop/Desamparado/Solvers/2024/sequential/Timed_Kissatsc2024"/makefile
	rm -f "/home/arthur/Desktop/Desamparado/Solvers/2024/sequential/Timed_Kissatsc2024"/src/makefile
	-$(MAKE) -C "/home/arthur/Desktop/Desamparado/Solvers/2024/sequential/Timed_Kissatsc2024/build" clean
	rm -rf "/home/arthur/Desktop/Desamparado/Solvers/2024/sequential/Timed_Kissatsc2024/build"
coverage:
	$(MAKE) -C "/home/arthur/Desktop/Desamparado/Solvers/2024/sequential/Timed_Kissatsc2024/build" coverage
format:
	$(MAKE) -C "/home/arthur/Desktop/Desamparado/Solvers/2024/sequential/Timed_Kissatsc2024/build" format
test:
	$(MAKE) -C "/home/arthur/Desktop/Desamparado/Solvers/2024/sequential/Timed_Kissatsc2024/build" test
.PHONY: all clean coverage format kissat test tissat
