all:
	$(MAKE) -C "/home/arthur/Desktop/Desamparado/SAT solvers/2024/sequential/kissat-sc2024/archive/kissat-sc2024-d776b9e1/build"
kissat:
	$(MAKE) -C "/home/arthur/Desktop/Desamparado/SAT solvers/2024/sequential/kissat-sc2024/archive/kissat-sc2024-d776b9e1/build" kissat
tissat:
	$(MAKE) -C "/home/arthur/Desktop/Desamparado/SAT solvers/2024/sequential/kissat-sc2024/archive/kissat-sc2024-d776b9e1/build" tissat
clean:
	rm -f "/home/arthur/Desktop/Desamparado/SAT solvers/2024/sequential/kissat-sc2024/archive/kissat-sc2024-d776b9e1"/makefile
	rm -f "/home/arthur/Desktop/Desamparado/SAT solvers/2024/sequential/kissat-sc2024/archive/kissat-sc2024-d776b9e1"/src/makefile
	-$(MAKE) -C "/home/arthur/Desktop/Desamparado/SAT solvers/2024/sequential/kissat-sc2024/archive/kissat-sc2024-d776b9e1/build" clean
	rm -rf "/home/arthur/Desktop/Desamparado/SAT solvers/2024/sequential/kissat-sc2024/archive/kissat-sc2024-d776b9e1/build"
coverage:
	$(MAKE) -C "/home/arthur/Desktop/Desamparado/SAT solvers/2024/sequential/kissat-sc2024/archive/kissat-sc2024-d776b9e1/build" coverage
format:
	$(MAKE) -C "/home/arthur/Desktop/Desamparado/SAT solvers/2024/sequential/kissat-sc2024/archive/kissat-sc2024-d776b9e1/build" format
test:
	$(MAKE) -C "/home/arthur/Desktop/Desamparado/SAT solvers/2024/sequential/kissat-sc2024/archive/kissat-sc2024-d776b9e1/build" test
.PHONY: all clean coverage format kissat test tissat
